---
## Usage: 
##   ansible-playbook s3-playbook.yml
- hosts: localhost
  connection: local
  gather_facts: False
  vars_file:
   - ./vars/sns-topic-subscritpion_vars.yml
  
  tasks:
  - debug: 
      msg: "{{ bucketname }}"

  - execute_lambda:
      function_arn: "funarnn"
      payload:
        s3BucketName: "{{ bucketname }}"
        REGION_NAME: "{{ regionname }}"
        ARN: "{{ topicARN }}"
    register: response  
 
    
